name: Commit Message Check

on:
  push:
    branches:
      - '**'

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install commitlint
        run: |
          yarn add --dev @commitlint/cli @commitlint/config-conventional

      - name: Lint commit messages
        run: |
          npx commitlint --from HEAD~1 --to HEAD --config @commitlint/config-conventional

