name: Prepare for release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v2.3.4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          registry-url: https://registry.npmjs.org/
          node-version: '16'

      # Install dependencies (required by Run tests step)
      - name: Install dependencies
        run: yarn install

  
      # Configure Git
      - name: Git configuration
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      # Update changelog unreleased section with new version
      - name: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: lui-ui/lui-vue