name: Run on PR Merged to Main and Publish to NPM
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  check-merged-pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v2.3.4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          registry-url: https://registry.npmjs.org/
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: yarn install
      
      # Build the project
      - name: Build
        run: yarn build
      
      # Get version from package.json
      - name: Get version
        id: package-version
        run: |
          echo "::set-output name=version::$(node -p "require('./package.json').version")"

      # Create a new GitHub release using the updated package.json version
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.package-version.outputs.version }}
          files: ./package.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      # Publish to NPM
      - name: Publish to NPM
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
